---
output:
  html_document:
    toc_float: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

<!-- ```{js} -->
<!-- $("#rStudioHeader").removeClass("alwaysShrunk"); -->
<!-- $("#pageContent").removeClass("standardPadding"); -->
<!-- ``` -->


<h2>**OxShef: Charts** provides advice on how to select the most appropriate charts for your data and how to avoid common mistakes when visualising data.</h2>

<hr>

<div class="row align-items-center">

<div class="col-sm-4 align-self-center">

[Charts](charts.html) are the most general purpose type of visualisation and include barcharts, linecharts, scatter plots, histograms...

<center>
```{r}
library("highcharter")
library("tidyverse")
my_data <- tribble(
  ~category, ~subcategory, ~value,
  "Mammal", "human", 3,
  "Mammal", "non-human", 4,
  "Reptile", "snake", 6,
  "Reptile", "iguana", 8
)
my_data %>%
  hchart(
    type = "bar",
    hcaes(
      x = category,
      y = value
    )
  ) %>%
  hc_size(width = "300px", height = "200px")
```
</center>

</div>

<div class="col-sm-4 align-self-center">

[Maps and geographic visualisations](geoviz_maps.html) require specially formatted data and include scatter geo plots, choropleth, weather maps...
<center>
```{r, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
library("tidyverse")
library("leaflet")
library("sf")
library("gapminder")

geojson_worldmap <- st_read("https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json",
                            quiet = TRUE)
geojson_worldmap <- invisible(geojson_worldmap %>%
  left_join(gapminder %>%
               filter(year == max(year)) , by = c("name" = "country")) %>%
  filter(name != "Antarctica"))
palette_pop <- colorNumeric("YlOrBr" , geojson_worldmap$pop, na.color = "#c0c1c4")
geojson_worldmap %>%
  leaflet(width = "300px",
          height = "200px") %>%
  addPolygons(fillColor = ~palette_pop(pop),
              fillOpacity = 0.8,
              color = "#000",
              weight = 1,
              label = ~name)
```
</center>
</div>

<div class="col-sm-4 align-self-center">

[Network visualisations](networks.html) or graph are amongst the less general purpose visualisations, alongside [time series](timeseries.html) and [others](other.html)...

<center>
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library("tidyverse")
library("visNetwork")
library("igraph")

my_nodes <- tribble(
  ~id, ~label, ~color, ~size,
  1, "Character A", "purple", 10,
  2, "Character B", "purple", 13,
  3, "Character C", "orange", 17,
  4, "Character D", "orange", 12,
  5, "Character E", "purple", 17,
  6, "Character Z", "green", 10
)

my_edges <- tribble(
  ~from, ~to, ~width,
  1, 2, 5,
  # 2, 1, 5,
  3, 1, 1,
  # 1, 3, 1,
  4, 1, 6,
  # 1, 4, 6,
  4, 2, 3,
  # 2, 4, 3,
  5, 2, 2,
  # 2, 5, 2,
  5, 3, 5,
  # 3, 5, 5,
  5, 6, 5
  # 6, 5, 5
)
visNetwork(my_nodes,
           my_edges,
           width = "200px",
           height = "200px") %>%
  visOptions(highlightNearest = list(enabled = TRUE, degree = 1)) %>%
  visInteraction(zoomView = FALSE)
```
</center>
</div>

</div>

<hr>

<h2>**OxShef: Tools** provides an overview of several [visualisation tools](https://tools.oxshef.io) widely used in academia. The flowchart below is designed to guide you whether our resources can help you visualise your dataset:</h2> 

```{r tool-selection-css, results="asis", echo=FALSE}
cat("
<style>
#mermaidChart0 { 
    min-height: 900px;
    min-width: 800px;
}
</style>
")
```

```{r tool-selection-flowchart, echo = FALSE, fig.height=6}
# library("DiagrammeR")
# 
# oxshef_flowchart <- DiagrammeR("graph TB;
#            A{Is your data public?} -- yes -->doiQuestion;
#            A -- no -->B[<center><b>Oxshef: dataviz</b> exclusively supports researchers in <br> the visualisation and promotion of <br> public datasets.</center>];
#            doiQuestion{<center>Is your dataset published<br> to a DOI-issuing data repository?</center>};
#            doiNotIssued[<center>Please ensure to deposit your data<br> in a DOI-issuing repository</center>]
#            doiQuestion -- yes --> externalDataQuestion;
#            doiQuestion -- no --> doiNotIssued;
#            externalDataQuestion{<center>Does your visualisation tool <br> allow data to be pulled from <br> your data repository?</center>};
#            externalDataSupported[<center>Excellent!<br> Our resources are designed for you!</center>];
#            externalDataUnsupported[<center>We recommend <b>not</b> using these tools</center>];
#            externalDataUnknown[<center>Refer to our <br>http://oxshef-charts.netlify.com/tools.html page</center>];
#            externalDataQuestion -- yes -->externalDataSupported;
#            externalDataQuestion -- no -->externalDataUnsupported;
#            externalDataQuestion -- I don't know -->externalDataUnknown",
#            width = "100%",
#            height = "900px")
# library("htmltools")
# 
# div(oxshef_flowchart)
library("tidyverse")
library("visNetwork")
library("emo")

nodes <- tribble(
  ~id, ~label, ~title, ~shape, ~size, ~color,
  1, "Is your data public?", NA, "diamond", 25, "#97C2FC",
  2, ji("white_check_mark"), NA, "dot", 5, "green",
  3, ji("x"), NA, "dot", 5, "red",
  4, "Reproducible dataviz require Open Data. \nLearn more at oxshef.io", "<a href='https://oxshef.io' target='_blank'>oxshef.io</a>", "square", 25, "#97C2FC",
  5, "Does your dataset \nhave a DOI?", NA, "diamond", 25, "#97C2FC",
  6, ji("x"), NA, "dot", 5, "red",
  7, ji("white_check_mark"), NA, "dot", 5, "green",
  8, "Visit repositories.oxshef.io \nto learn about DOI", "<a href='https://repositories.oxshef.io' target='_blank'>repositories.oxshef.io</a>", "square", 25, "red",
  9, "Does your dataviz\n pull data from a data repository?", NA, "diamond", 25, "#97C2FC",
  10, ji("white_check_mark"), NA, "dot", 5, "green",
  11, ji("x"), NA, "dot", 5, "red",
  12, "You have a reproducible \ndataviz workflow!", NA, "dot", 25, "green",
  13, "Visit tools.oxshef.io \nto learn more", "<a href='https://tools.oxshef.io' target='_blank'>tools.oxshef.io</a>", "dot", 25, "red"
)

edges <- tribble(
  ~from, ~to,
  1, 2,
  1, 3,
  3, 4,
  2, 5,
  5, 7,
  5, 6,
  6, 8,
  7, 9,
  9, 10,
  9, 11,
  10, 12,
  11, 13
)

visNetwork(nodes, edges, width = "100%", height = "500px") %>% 
  visEdges(color = "#97C2FC") %>%
  visNodes(font = list(size = 16)) %>%
  visInteraction(dragNodes = FALSE, dragView = FALSE, selectable = FALSE) %>%
  visHierarchicalLayout(direction = "LR", 
                        levelSeparation = 180, 
                        sortMethod = "directed",
                        blockShifting = FALSE,
                        edgeMinimization = FALSE)

```


