---
title: "Time series"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    includes:
      before_body: [includes/include_header.html, includes/include_header_navpage.html]
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# Time series

Time series are used for communicating data that changes over time, where the x axis [typically] of the chart is specially designed for the time scale appropriate for your data:

- Inter-day datasets (e.g. stock prices, thermostat measurements) require hour:minute:second formatted axes.
- Annualised datasets (e.g. company performance numbers, global temperature) require month:day formatted axes
- Historical datasets require axes that span both BC and AD dates.
- Timelines for historical/geological periods require axes that allow some overlap and are a specialised type of time series visualisation.

Before starting to design your time series visualisations ensure that your data is well formatted for visualisation, most tools expect specific formats for dates/times. The most general purpose standard for formatting dates/times is [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), which can be summarised into the following guidance:

- Date format: yyyy-mm-dd
- Time format: hh:mm:ss
- Combined date and time (UTC time zone) format: yyyy-mm-ddThh:mm:ss+00:00





