---
title: "Tools"
output:
  html_document:
    toc: false
    toc_float:
      collapsed: false
    includes:
      before_body: [includes/include_header.html, includes/include_header_navpage.html]
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```


<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

# Visualisation Tools {.tabset}

Visit 

```{r viz-tools-DT, echo = FALSE}
library("tidyverse")
library("DT")
library("readxl")

fa_scripting <- "<i class='fa fa-file-code fa-2x'></i>"
fa_pointAndClick <- "<i class='fa fa-hand-pointer fa-2x'></i>"

fa_icons <- tribble(
  ~tool.type, ~type,
  "Scripting", "<i class='fa fa-file-code fa-2x'></i>",
  "Point and Click", "<i class='fa fa-hand-pointer fa-2x'></i>"
)


download.file(url = "https://github.com/OxShef/oxshef_tools/blob/master/oxshef-viz-tools.xlsx?raw=true", destfile = "oxshef-viz-tools.xlsx")

oxshef_viz_tools <- read_xlsx("oxshef-viz-tools.xlsx")

unlink("oxshef-viz-tools.xlsx")

oxshef_viz_tools %>%
  arrange(tool) %>%
  mutate(tool = paste0("<a href='", url,"' target='_blank'>", tool, "</a>")) %>%
  left_join(fa_icons) %>%
  select(-url, -tool.type) %>%
  mutate(external.data.support = ifelse(external.data.support,
                                         "<i class='fas fa-circle'></i>",
                                         "<i class='far fa-circle'></i>")) %>%
  datatable(escape = FALSE,
            rownames = FALSE,
            colnames = c("Visualisation Tool",
                         "Brief Description",
                         "Allows external data to be accessed?",
                         "Type of tool"),
            options = list(
              scrollX = TRUE,
                autoWidth = TRUE,
  columnDefs = list(list(width = '100px', targets = c(0,2)),
                    list(className = 'dt-center', targets = c(0,2,3))),
              dom = "t"
            ),
  width = "100%")
```

## Which chart should I use flowchart

```{r tool-selection-css, results="asis", echo=FALSE}
cat("
<style>
#mermaidChart0 { 
    min-height: 900px;
    min-width: 800px;
}
</style>
")
```

```{r tool-selection-flowchart, echo = FALSE, fig.height=6}
library("DiagrammeR")

oxshef_flowchart <- DiagrammeR("graph TB;
           A{Is your data public?} -- yes -->doiQuestion;
           A -- no -->B[<center><b>Oxshef: dataviz</b> exclusively supports researchers in <br> the visualisation and promotion of <br> public datasets.</center>];
           doiQuestion{<center>Is your dataset published<br> to a DOI-issuing data repository?</center>};
           doiNotIssued[<center>Please ensure to deposit your data<br> in a DOI-issuing repository</center>]
           doiQuestion -- yes --> externalDataQuestion;
           doiQuestion -- no --> doiNotIssued;
           externalDataQuestion{<center>Does your visualisation tool <br> allow data to be pulled from <br> your data repository?</center>};
           externalDataSupported[<center>Excellent!<br> Our resources are designed for you!</center>];
           externalDataUnsupported[<center>We recommend <b>not</b> using these tools</center>];
           externalDataUnknown[<center>Refer to our <br>http://oxshef-charts.netlify.com/tools.html page Twitter oxshef_dataviz</center>];
           externalDataQuestion -- yes -->externalDataSupported;
           externalDataQuestion -- no -->externalDataUnsupported;
           externalDataQuestion -- I don't know -->externalDataUnknown",
           width = "100%",
           height = "900px")
library("htmltools")

widgetframe::frameWidget(oxshef_flowchart)
```

