---
title: "Training, Tutorials and Templates"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
    includes:
      before_body: [includes/include_header.html, includes/include_header_navpage.html]
---

```{r include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Choosing visualisations

This website contains pages dedicated to five different categories of visualisation, where we attempt to provide some advice to help you choose appropriate visualisations for your data.

- [Charts](charts.html): These includes barcharts, piecharts, scatter plots and a host of other visualisations useful for visualising raw data, comparing datasets or communicating statistical properties of datasets.
- [Geoviz (Maps)](geoviz_maps.html): These include scatter geo plots and choropleth and are useful for visualising geographic data pertaining to planet Earth (whether that's physical, social or political data).
- [Networks](networks.html): These are visualisations designed to visually represent the connections between entities/individuals/nodes, for instance relations in a family tree or the collaborations between historical persons.
- [Time Series](time-series.html): These are useful for presenting the variation in data over time, often used for financial data.
- [Other Visualisations](other.html): These visualisations are difficult to other categories, including interactive tables and Venn diagrams.

In addition to these resources, we highly recommend the following online tools for helping to choose which visualisation is most appropriate for your data:

- [Financial Times' Visual Vocabulary](http://ft-interactive.github.io/visual-vocabulary/)
- [Visualising Data: Chart Directory](http://chartmaker.visualisingdata.com/)

## Advice on adding interactivity

When designing interactive data visualisations there is often an impulse to over-design and to add too many features. The IDN recommends following [Ben Shneiderman's mantra](https://doi.org/10.1109/VL.1996.545307):

- "Overview first, zoom and filter, then details-on-demand"

This advice translates into the following practical tips:

- Choose the most appropriate visualisation(s) for your data, if using multiple visualisations allow users to switch wholesale between them - for instance using different tabs.
- Enable zoom/pan controls in the visualisation
- Provide users with sliders, menus, buttons to filter the data shown within the visualisation
- Display tooltips when users mouseover/hover over data within a visualisation
- Provide summary details (including additional visualisations if appropriate) when the user clicks/selects data within the visualisation
